### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [SPTecPrzemek/Projekt116#1]
- [x] zadnych css’ow nie uzywasz wiec mozesz usunac dolaczanie ich w headzie
- [x] popraw czytelnosc wynikow. Obecnie jak api zwroci kilka wynikow to lista staje sie nieczytelna (wpisz w wyszukiwarke np ‘us’). Proponuje taka strukture:
    - Nazwa kraju: Australia
        - Jezyk: …
        - Populacja: …
    - Nazwa kraju: Austria
        - Jezyk: …
        - Populacja: … 
- [x] zmiany wypusc na nowym branchu i wystaw na githubie pull request do brancha master
